"""Small argument examples for on-demand help; identifiers are illustrative."""

NODE = {"scene": "res://main.tscn", "path": "."}
RUN_NODE = {"run_id": "returned-run-id", "path": "/root/Main"}
LOCAL = {"local": {**NODE, "property": "material_override"}}
EXAMPLES = {
    "get_guide": {"section": "tools", "tool": "create_nodes"},
    "create_project": {"project": "/absolute/path/game", "name": "My Game"},
    "install_plugin": {"project": "/absolute/path/existing-game"},
    "get_context": {"scope": "progress"},
    "get_operation_result": {"operation_id": "returned-operation-id", "wait_ms": 15000},
    "find_assets": {"mode": "list", "scope": "res://", "recursive": True},
    "delete_assets": {"action": {"preview": {"paths": ["res://unused.gd"]}}},
    "purge_deleted_assets": {"action": {"preview": {"deletion_ids": ["returned-deletion-id"]}}},
    "restore_assets": {"deletion_id": "returned-deletion-id"},
    "get_class_info": {"class": "Button", "member": "pressed"},
    "get_scene": {"scene": "res://main.tscn", "include": ["properties"], "properties": ["visible"]},
    "open_scene": {"scene": "res://main.tscn"},
    "create_scene": {"uri": "res://player.tscn", "root_class": "CharacterBody2D", "root_name": "Player"},
    "create_nodes": {"parent": NODE, "nodes": [{"name": "Start", "source": {"class": "Button"}, "properties": {"text": "Start"}}]},
    "update_nodes": {"changes": [{"node": {**NODE, "path": "Start"}, "set": {"text": "Play"}}]},
    "delete_nodes": {"nodes": [{**NODE, "path": "Unused"}]},
    "save_documents": {"uris": ["res://main.tscn"]},
    "undo_edit": {"edit_id": "returned-edit-id"},
    "get_resource": {"target": {"uri": "res://style.tres"}},
    "create_resource": {"class": "StandardMaterial3D", "save_as": "res://surface.tres"},
    "update_resource": {"target": LOCAL, "set": {"roughness": 0.8}},
    "read_scripts": {"documents": [{"uri": "res://player.gd"}]},
    "apply_script_changes": {"patch": "*** Begin Patch\n*** Add File: res://player.gd\n+extends CharacterBody2D\n+@export var speed: float = 200.0\n*** End Patch", "save": True},
    "resume_script_changes": {"operation_id": "returned-operation-id", "reload": "auto"},
    "update_signals": {"connect": [{"from": {**NODE, "path": "Start"}, "signal": "pressed", "to": NODE, "method": "_on_start_pressed"}]},
    "get_animation": {"node": {**NODE, "path": "AnimationPlayer"}, "animation": "idle"},
    "edit_animation": {"player": {**NODE, "path": "AnimationPlayer"}, "name": "idle", "create": True, "length": 1.0, "loop": True},
    "edit_animation_graph": {"tree": {**NODE, "path": "AnimationTree"}, "root_type": "state_machine", "states": [{"name": "Idle", "animation": "idle"}]},
    "preview_animation": {"player": {**NODE, "path": "AnimationPlayer"}, "name": "idle", "time": 0.5},
    "get_tilemap": {"layer": {**NODE, "path": "Ground"}, "limit": 100},
    "edit_tileset": {"target": {"local": {**NODE, "path": "Ground", "property": "tile_set"}}, "changes": [{"add_atlas": {"texture": "res://tiles.png", "key": "ground"}}]},
    "paint_tiles": {"layer": {**NODE, "path": "Ground"}, "cells": [{"cell": {"x": 0, "y": 0}, "tile": {"source_id": 0, "atlas": {"x": 0, "y": 0}}}]},
    "inspect_runtime": {"node": RUN_NODE, "properties": ["visible"]},
    "capture_viewport": {"viewport": {"kind": "editor_2d", "scene": "res://main.tscn"}, "framing": "scene"},
    "wait_for_condition": {"run_id": "returned-run-id", "condition": {"node": {"node": RUN_NODE, "exists": True}}},
    "get_diagnostics": {"uris": ["res://player.gd"]},
    "get_logs": {"kinds": ["error"], "limit": 20},
    "sample_performance": {"run_id": "returned-run-id", "duration_ms": 1000, "metrics": ["fps", "process_ms"]},
    "run_scene": {"scene": "res://main.tscn"},
    "stop_game": {"run_id": "returned-run-id"},
    "send_input": {"run_id": "returned-run-id", "events": [{"at_ms": 0, "event": {"action": {"action": "ui_accept", "pressed": True}}}, {"at_ms": 100, "event": {"action": {"action": "ui_accept", "pressed": False}}}], "observe": [{"node": RUN_NODE, "properties": ["visible"]}], "capture_after": True},
    "inspect_debugger": {"run_id": "returned-run-id"},
    "set_breakpoints": {"breakpoints": [{"uri": "res://player.gd", "line": 10}]},
    "debug_control": {"run_id": "returned-run-id", "action": "pause"},
    "get_settings": {"include": ["input_actions"]},
    "get_export_presets": {},
    "import_assets": {"files": [{"source": "file:///absolute/path/tiles.png", "destination": "res://tiles.png"}]},
    "move_assets": {"moves": [{"from": "res://player.gd", "to": "res://actors/player.gd"}]},
    "update_settings": {"settings": {"application/run/main_scene": "res://main.tscn"}},
    "export_build": {"preset": "Linux", "output": "file:///absolute/path/build/game.x86_64"},
}
